document.addEventListener("DOMContentLoaded", function() {
    // Determine base URL based on environment (localhost vs GitHub Pages)
    var isLocalhost = window.location.hostname === "localhost" || window.location.hostname === "127.0.0.1";
    var baseUrl = isLocalhost ? "" : "/PyEyesWeb";

    // Attempt to fetch the versions.json generated by mike
    fetch(baseUrl + "/versions.json").then(response => {
        if (!response.ok) return null;
        return response.json();
    }).then(versions => {
        if (!versions || versions.length === 0) return;
        
        // Find the current version from the URL path. 
        var pathSegments = window.location.pathname.split('/').filter(p => p !== "");
        // If localhost: /dev/ -> pathSegments[0] is "dev"
        // If GitHub: /PyEyesWeb/dev/ -> pathSegments[1] is "dev"
        var currentVersion = isLocalhost ? pathSegments[0] : pathSegments[1]; 
        
        if (!currentVersion) {
            currentVersion = versions[0].version; // fallback if at root
        }
        
        var select = document.createElement("select");
        select.style.margin = "10px auto";
        select.style.display = "block";
        select.style.width = "90%";
        select.style.padding = "5px";
        select.style.color = "#000";
        select.style.borderRadius = "3px";
        select.style.border = "1px solid #ccc";
        
        versions.forEach(function(version) {
            var option = document.createElement("option");
            option.value = version.version;
            option.text = "Version: " + version.title;
            if (version.version === currentVersion || version.aliases.includes(currentVersion)) {
                option.selected = true;
            }
            select.appendChild(option);
        });

        select.addEventListener("change", function() {
            window.location.href = baseUrl + "/" + this.value + "/";
        });

        // Add the dropdown to the readthedocs sidebar search box or navigation container
        var searchBox = document.querySelector(".wy-side-nav-search");
        if (searchBox) {
            searchBox.appendChild(select);
        }
    }).catch(e => console.error("Error loading versions.json:", e));
});
