name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout repo (code + docs)
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # 3. Install docs dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]   # installs mkdocs and all extras

      # 4. Push to gh-pages branch
      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force
